namespace Wasel.NotificationService.Enums;

public enum NotificationType
{
    DELIVERY_ASSIGNED,
    DRIVER_ARRIVING,
    PAYMENT_CONFIRMED,
    COMPLAINT_CREATED,
    COMPLAINT_RESOLVED,
    NEW_MESSAGE,
    DELIVERY_STATUS_CHANGED,
    DRIVER_DOSSIER_APPROVED,
    DRIVER_DOSSIER_REJECTED
}
